name: Swift

on: [push]

jobs:
  build:

    runs-on: macOS-latest

    steps:
    - uses: actions/checkout@master
    - name: Install Dependences
      run: |
        pod repo update
        pod install
      shell: bash
    - name: Build
      run: xcodebuild -scheme "QuickFin" -allowProvisioningUpdates build
